Title: Dungeon Blitz
Alternate Titles: null
Library: arcade
Series: null
Developer: Blue Mammoth Games
Publisher: null
Play Mode: Multiplayer
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: null
Platform: Flash
Status: Playable
Application Path: FPSoftware\Flash\flashplayer_32_sa.exe
Launch Command: http://db.bmgstatic.com/p/cbv/DungeonBlitz.swf?fv=cbq&gv=cbv
Game Notes: null
Original Description: null
Curation Notes: null
Additional Applications: {}
