Title: Dungeon Blitz
Library: arcade
Developer: Blue Mammoth Games
Play Mode: Multiplayer
Languages: en
Tags: MMO
Tag Categories: default
Primary Platform: Flash
Platforms: Flash
Status: Playable
Application Path: FPSoftware\Flash\flashplayer_32_sa.exe
Launch Command: http://db.bmgstatic.com/p/cbv/DungeonBlitz.swf?fv=cbq&gv=cbv
Original Description: >-

  Dungeon Blitz is a Flash based side-scrolling MMO set in a realm on the
  crossroads between the Human World and the Sleeping Lands, an underworld of
  legendary creatures and civilizations whose time has passed. The crossroads is
  one of just a few places on Earth where the ancient Sleeping Lands still touch
  the Human World. You are a bold adventurer on journey to unlock the mystery
  and secrets of the buried world. Dungeon Blitz is free-to-play and easy to
  try.
UUID:
Group: ""
Additional Applications: {}
